### ISSUE TITLE
"pop" and "shift" don't exist on the baobab api

### ISSUE THREAD

**Issue by overture8** [christianalfoni/cerebral-baobab#11]
I'm having an issue using `pop` and `shift`. They seem to proxy to the baobab library - however, from what I can see, `pop` and `shift` don't exist on the baobab api.

Not sure what the solution is here until baobab supports these? Maybe use `splice` like suggested here: https://github.com/Yomguithereal/baobab/issues/295?

**Comment by christianalfoni** [comment]
Hi @overture8,

I just have to slice() the arrays to make a duplicate, will release fix for that :-) Thanks!

**Comment by christianalfoni** [comment]
Allright, running with the splicing strategy. I see that this will be fixed in next release of Baobab. So can change it then :-)

Will be part of next release
