### ISSUE TITLE
splice isn't returning deleted values

### ISSUE THREAD

**Issue by AndreasArledal** [christianalfoni/cerebral-baobab#13]
Array.prototype.splice normally returns deleted values.

``` javascript
// state = { foo: [1, 2, 3, 4] }
state.splice('foo', 1, 2); // [2, 3]
```

**Comment by AndreasArledal** [comment]
Was looking into this and both baobab and immutable.js seems to be returning the saved values rather than the deleted values, which makes totally sense in an immutable world.

What confused me was the state documentation for cerebral saying `// Normal array splice`. I'm closing this and will open an issue or PR for changing documentation instead.

**Comment by christianalfoni** [comment]
Awesome, thanks :-)
