### ISSUE TITLE
decoupling controller from model

### ISSUE THREAD

**Issue by marcel-ernst** [christianalfoni/cerebral-baobab#17]
Hi,
in my opinion it'll be better to inject the controller via an setter or the controller binds his events in his own instance. So you can use the model standalone (for whatever) and it's absolut clear, that Model() returns an instance an not a "factory".
I was trying to write a TypeScript definition file for this and in the actual version I have to use the type any, because the type changes on runtime.

actual situation:

``` javascript
// model/index.js
var Model = function (initialState, options) {
    var model = function (controller) {
        controller.on('reset', function () {
            tree.set(initialState);
        });

        controller.on('seek', function (seek, recording) {
            // ...
        });

        return {
            // ...
        }
    }

    return model;
}

// controller repo
var Controller = function (Model, services) {
    var model = Model(controller);
}
```

my proposal:

``` javascript
// model/index.js
var Model = function (initialState, options) {
    var model = function () {
    }

    return model;
}



var Controller = function(model, services) {
    model.injectController(this);

    // or my favourite
    controller.on('reset', function() {
        model.reset();
    });

    controller.on('seek', function() {
        model.seek();
    });
}
```

What do you think?

**Comment by Guria** [comment]
does it solved now?

**Comment by christianalfoni** [comment]
Cerebral 2.0 will probably only have one model layer where you get the best of immutable-js and baobab. So lets hold on with this :)
