### ISSUE TITLE
pop/shift broken

### ISSUE THREAD

**Issue by tnrich** [christianalfoni/cerebral-baobab#18]
Currently pop/shift doesn't work with the cerebral-baobab model. I think the way it was implemented caused the immutable tree to be mutated which broke things. 

@Yomguithereal implemented a fix though on the baobab side to handle pop/shift. So ideally once that is tested, we can just update the cerebral pop/shift to use those new methods.

**Comment by christianalfoni** [comment]
Jup, I have a temp fix in there which will be released very soon
