### ISSUE TITLE
Support validation to a greater degree

### ISSUE THREAD

**Issue by saulshanabrook** [christianalfoni/cerebral-baobab#2]
I am using the `validate` option in baobab and that is working great. However, I would love to be able to handle when the tree is called with something invalid. In baobab, you [would do](https://github.com/Yomguithereal/baobab/tree/v2#tree-level-1):

```
tree.on('invalid', function(e) {
  console.log('Error:', e.data.error);
});
```

So it would be nice to be able to access this in some way from cerebral, maybe by using a cerebral event.

I also opened https://github.com/christianalfoni/cerebral/issues/77 which would address this by supporting validation natively within cerebral and so would render this not neccesary.

**Comment by christianalfoni** [comment]
I think we should just expose the tree for now, and see where the validation goes. Published new version now, check the docs :-)
