### ISSUE TITLE
Add setWhere() to mutations

### ISSUE THREAD

**Issue by bfitch** [christianalfoni/cerebral-baobab#23]
Had the idea of adding `setWhere` to wrap up a lot of low level manipulation required when selectively updating or deleting data based on a given query attribute. It works similarly to `findWhere()`.

``` js
setWhere('todos', {title: 'boo'}, {completed: true}); 
// sets completed: true on any object with title 'boo' 
```

Fuller example of the API:

``` js
const baobab = new Baobab({
  todos: [{id: 1, title: 'boo'}, {id: 2, title: 'boo'}],
  currentUser: { first_name: 'boo'}
});

// unsetting (deleting) by query
setWhere('todos', {title: 'boo'}); // unsets any object with title 'boo'
setWhere('currentUser', {first_name: 'boo'}); // if the object's first name is 'boo' sets currentUser to null

//setting by query

setWhere('todos', {title: 'boo'}, {completed: true}); // sets completed: true on any object with title 'boo' 
setWhere('currentUser', {first_name: 'boo'}, {isAdmin: true}); // if currentUser's first name is 'boo', sets isAdmin to true

JSON.stringify(baobab.get(),null,2)  // output:

{
  "todos": [
    {
      "id": 1,
      "title": "boo",
      "completed": true
    },
    {
      "id": 2,
      "title": "boo",
      "completed": true
    }
  ],
  "currentUser": {
    "first_name": "boo",
    "isAdmin": true
  }
}
```

Implementation:

``` js
function setWhere(path, attrs, newAttrs = null) {
  const key    = Object.keys(attrs).pop();
  const value  = attrs[key]
  const cursor = baobab.select(path);

  if (Array.isArray(cursor.get())) {
    setCollection(cursor, key, value, newAttrs);
  } else {
    setObject(cursor, key, value, newAttrs);
  }
}

function setObject(cursor, key, value, newAttrs) {
  if (cursor.get()[key]) {
    !newAttrs ? cursor.set(null) : cursor.deepMerge(newAttrs);
  }
}

function setCollection(collection, key, value, newAttrs) {
  const items   = collection.get().filter(item => item[key] === value);
  const indices = items.map(item => collection.get().indexOf(item));
  indices.forEach(i => {
    if (!newAttrs) {
      items.map(item => collection.unset(collection.get().indexOf(item)));
    } else {
      collection.splice([i, 1, Object.assign({}, items[i], newAttrs)]);
    }
  });
}
```

**Comment by bfitch** [comment]
Pull request here: https://github.com/cerebral/cerebral-model-baobab/pull/24

**Comment by christianalfoni** [comment]
Awesome! You wanna do the same for immutable JS as well? :D

**Comment by Guria** [comment]
Maybe better to make it as universal provider?

**Comment by christianalfoni** [comment]
Hm... interesting. Yeah, that way we could also move the `cursor` thingy as a universal provider. You wanna have a go at that @bfitch ? Go to Cerebral project and create a `contextProvider` instead for this feature? :) I can fix the `cursor` thingy. That was your thoughts as well @Guria ?

**Comment by Guria** [comment]
@christianalfoni do you want to put it in `cerebral/providers` as not loaded by default? or maybe it's better to be part of `cerebral-addons`? what do you think?

**Comment by christianalfoni** [comment]
I am thinking it should be in `cerebral/providers` and loaded by default. Feeling we are going down the "babel" config path here. Would be nice to make it official part of API, very useful thing :)

**Comment by bfitch** [comment]
Hmmm....I haven't done anything with or really looked into providers yet-- beyond the docs. But, I'd be happy to move this wherever you guys think it makes sense. I will probably need a little guidance, though :)

I'll just add that I think APIs like this should be part of "default" cerebral...whichever way we implement it. This kind of stuff is pretty fundamental to how we all need to update state and it applies to almost any cerebral project. It should be as "core" as `findWhere` or `push`, in my opinion. 😎

**Comment by christianalfoni** [comment]
Yeah, fundemental abstractions that uses the core mutators and accessors should work across packages. So nice to use providers for that. Poke me on discord Brian and we can have a short session get you going with Providers, maybe it will inspire you to other things as well :-)
