### ISSUE TITLE
Run `tree.commit()` after sync signal executed

### ISSUE THREAD

**Issue by Guria** [christianalfoni/cerebral-baobab#3]
`Baobab` has [recommendation](https://github.com/Yomguithereal/baobab-react/tree/v2#common-pitfalls) to do `tree.commit()` when changing value bound with controlled input.

Maybe `cerebral-baobab` could extend sync signal run to do `tree.commit()` automatically.
Likely would require changes in `cerebral` itself.

**Comment by christianalfoni** [comment]
V2 is soon arriving and currently everything runs as expected without any configuration to Baobab. we could introduce hooks to models on "beforeSignal" and "afterSignal" where the model could to stuff... like `tree.commit()`, but it should not be necessary. Lets keep it open to make sure though :-)

**Comment by christianalfoni** [comment]
Okay, reopen if you meet any issues. :-)
